/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS_CRUD;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * @author rini sukma ayu
 */
public class FromSupplierCategory extends javax.swing.JFrame {
private Connections conn = new Connections();

private DefaultTableModel model;
    private Object tblcategory;

private void autonumber(){
    try{
        Connection c = Connections.getConnections();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM supplier_category ORDER BY " + "id_SCategory DESC";
        ResultSet r = s.executeQuery(sql);
        if(r.next()){
            String CategoryCode = r.getString("SCategory_Code").substring(2);
            String CS = ""+ (Integer.parseInt("SCategory_code")+1);
            String Zero = "";
            if(CS.length()== 1){
                Zero = "00";
            }else if (CS.length()==2){
                Zero= "0";
            }else{
                Zero="";
            }
            txtCategoryCode.setText("CS" + Zero + CS);
        }else{ txtCategoryCode.setText("CS001");
        }
        r.close();
        s.close();
    }catch(Exception e){
        System.out.println("Auto Number Eror");
    }
}
private void clear(){
    txtCategoryName.setText("");
}

public void loadData(){
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    try{
        Connection c = Connections.getConnections();
        Statement s = c.createStatement();     
        String sql = "SELECT * FROM supplier_category";
        ResultSet r = s.executeQuery(sql);
        
        while(r.next()){
            Object[] o = new Object[3];
            o [0] = r.getString("id_SCategory");
            o [1] = r.getString("SCategory_Code");
            o [2] = r.getString("SCategory_nama");
            model.addRow(o);
        }
        r.close();
        s.close();
    }catch(SQLException e){
        System.out.println("Something wrong");
                    
        }
}

    /**
     * Creates new form FromSupplierCategory
     */
    public FromSupplierCategory() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtCategoryCode.setEnabled(false);
        model = new DefaultTableModel();
        tblcategory.setModel(model);
        
        //add colum table
        model.addColumn("ID");
        model.addColumn("Category Code");
        model.addColumn("Category Name");
        
        loadData();
        autonumber();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbCategorySupplier = new javax.swing.JLabel();
        lbCategoryName = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        txtCategoryCode = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcategory = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Category Supplier");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lbCategorySupplier.setText("Category Code");

        lbCategoryName.setText("Category Name");

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        txtCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryNameActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        tblcategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Category Code", "Category Name"
            }
        ));
        tblcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcategoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblcategory);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCategoryName)
                                    .addComponent(lbCategorySupplier))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCategoryCode, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtCategoryName)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSave)
                                .addGap(7, 7, 7)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategorySupplier)
                    .addComponent(txtCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCategoryName)
                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btDelete)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        String CategoryCode =txtCategoryCode.getText();
        String CategoryName =txtCategoryName.getText();
        try{
            Connection c = Connections.getConnections();
            String sql = "SELECT * FROM supplier_category(SCategory_code,"
                    + "SCategory_nama) VALUES (?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, CategoryCode);
            p.setString(2, CategoryName);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null,"Data Successful Saved");
        }catch(SQLException e){
            System.out.println("Something wrong");
        }finally{
            loadData();
            autonumber();
            clear();
            
        }        
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int i = tblcategory.getSelectedRow();
        if(i == -1){
            return;
        } 
        String id = (String)model.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null,
                "Sure this data will be delet?",
                "Confrim",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE); 
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = Connections.getConnections();
                String sql = "DELETE FROM supplier_category WHERE id_SCategory = ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, id);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "The data been deleted");
            }catch(SQLException e){
                System.out.println("Delete Eror");
            }finally{
                loadData();
                autonumber();
                btSave.setEnabled(true);
            }
    }//GEN-LAST:event_btDeleteActionPerformed

        
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryNameActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tblcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcategoryMouseClicked
        // TODO add your handling code here:
                btSave.setEnabled(false);
        int i = tblcategory.getSelectedRow();
        if(i == -1){
            return;
        }
        String CategoryCode = (String)model.getValueAt(i, 1);
        txtCategoryCode.setText(CategoryCode);
        String CategoryName = (String)model.getValueAt(i, 2);
        txtCategoryName.setText(CategoryName);
    }//GEN-LAST:event_tblcategoryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int i = tblcategory.getSelectedRow();
        if (i == -1){
            return;
        } 
         String id = (String)model.getValueAt(i, 0);
        String CategoryCode = txtCategoryCode.getText();
        String CategoryName = txtCategoryName.getText();
        try{
            Connection c = Connections.getConnection();
            String sql = "UPDATE supplier_category SET SCategory_code =,SCategory_name =? "
                    + "WHERE id_SCategory";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(2, CategoryCode);
            p.setString(2, CategoryName);
            p.setString(3, id);
            p.close();
             JOptionPane.showMessageDialog(null,"The data has been update");
        }catch(SQLException e){
            System.out.println("Update Error");
        }finally{
            loadData();
            autonumber();
            clear();          
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         clear();
        loadData();
        btSave.setEnabled(true);
        autonumber();    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromSupplierCategory().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbCategoryName;
    private javax.swing.JLabel lbCategorySupplier;
    private javax.swing.JTable tblcategory;
    private javax.swing.JTextField txtCategoryCode;
    private javax.swing.JTextField txtCategoryName;
    // End of variables declaration//GEN-END:variables
}

}
